name: moana_plots
channels:
  - conda-forge
  - Microsoft
  - defaults
dependencies:
  - anyio=4.2.0=py312hca03da5_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h80987f9_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=py312hca03da5_0
  - attrs=23.1.0=py312hca03da5_0
  - babel=2.11.0=py312hca03da5_0
  - beautifulsoup4=4.12.2=py312hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.7=py312ha86b861_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotli-python=1.0.9=py312h313beb8_7
  - bzip2=1.0.8=h80987f9_5
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.3.11=hca03da5_0
  - cartopy=0.22.0=py312hd77ebd4_0
  - certifi=2024.2.2=py312hca03da5_0
  - cffi=1.16.0=py312h80987f9_0
  - cftime=1.6.2=py312ha86b861_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py312h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - debugpy=1.6.7=py312h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - erddapy=2.2.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.5.0=h313beb8_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - geos=3.9.1=hc377ac9_1
  - gettext=0.21.0=h13f89a0_1
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - glob2=0.7=pyhd3eb1b0_0
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - h11=0.14.0=py312hca03da5_0
  - hdf4=4.2.13=h5e329fb_3
  - hdf5=1.12.1=h05c076b_3
  - httpcore=1.0.2=py312hca03da5_0
  - httpx=0.26.0=py312hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.4=py312hca03da5_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.22.2=pyh707e725_0
  - ipywidgets=8.1.2=py312hca03da5_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py312hca03da5_0
  - jpeg=9e=h80987f9_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py312hca03da5_0
  - jsonschema-specifications=2023.7.1=py312hca03da5_0
  - jupyter=1.0.0=py312hca03da5_9
  - jupyter-lsp=2.2.0=py312hca03da5_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_console=6.6.3=py312hca03da5_1
  - jupyter_core=5.5.0=py312hca03da5_0
  - jupyter_events=0.8.0=py312hca03da5_0
  - jupyter_server=2.10.0=py312hca03da5_0
  - jupyter_server_terminals=0.4.4=py312hca03da5_1
  - jupyterlab=4.0.11=py312hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py312hca03da5_0
  - jupyterlab_widgets=3.0.10=py312hca03da5_0
  - kiwisolver=1.4.4=py312h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.5.0=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h1a28f6b_2
  - libllvm14=14.0.6=h7ec7a93_3
  - libnetcdf=4.8.1=h0fce390_4
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libpq=12.17=h02f6b3c_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h27ca646_1
  - libssh2=1.10.0=h02f6b3c_2
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.10.4=h0dcf63f_1
  - libzip=1.8.0=h62fee54_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.3=py312h80987f9_0
  - matplotlib=3.8.0=py312hca03da5_0
  - matplotlib-base=3.8.0=py312hd77ebd4_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=py312hca03da5_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=ha71a6ea_2
  - nbclient=0.8.0=py312hca03da5_0
  - nbconvert=7.10.0=py312hca03da5_0
  - nbformat=5.9.2=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - netcdf4=1.6.2=py312h6eb1a2a_0
  - notebook=7.0.8=py312hca03da5_0
  - notebook-shim=0.2.3=py312hca03da5_0
  - numexpr=2.8.7=py312h0f3ea24_0
  - numpy=1.26.4=py312h7f4fdc5_0
  - numpy-base=1.26.4=py312he047099_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.2.1=h0d3ecfb_1
  - overrides=7.4.0=py312hca03da5_0
  - packaging=23.2=py312hca03da5_0
  - pandas=2.2.1=py312hd77ebd4_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hb066dcc_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py312h80987f9_0
  - pip=23.3.1=py312hca03da5_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - ply=3.11=py312hca03da5_1
  - proj=9.3.1=h805f6d4_0
  - prometheus_client=0.14.1=py312hca03da5_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - protobuf=3.20.3=py312h313beb8_0
  - psutil=5.9.0=py312h80987f9_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.0.9=py312hca03da5_0
  - pyproj=3.6.1=py312h4b40952_0
  - pyqt=5.15.10=py312h313beb8_0
  - pyqt5-sip=12.13.0=py312h80987f9_0
  - pyshp=2.3.1=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.2=h99e199e_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py312hca03da5_0
  - python-json-logger=2.0.7=py312hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py312hca03da5_0
  - pyyaml=6.0.1=py312h80987f9_0
  - pyzmq=25.1.2=py312h313beb8_0
  - qt-main=5.15.2=h0917680_10
  - qtconsole=5.5.1=py312hca03da5_0
  - qtpy=2.4.1=py312hca03da5_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py312hca03da5_0
  - requests=2.31.0=py312hca03da5_1
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rpds-py=0.10.6=py312hf0e4da2_0
  - send2trash=1.8.2=py312hca03da5_0
  - setuptools=68.2.2=py312hca03da5_0
  - shapely=2.0.1=py312ha8c8ce4_1
  - sip=6.7.12=py312h313beb8_0
  - siphon=0.9=pyhd8ed1ab_2
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py312hca03da5_0
  - soupsieve=2.5=py312hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.17.1=py312hca03da5_0
  - tinycss2=1.2.1=py312hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - tornado=6.3.3=py312h80987f9_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.1.0=py312hca03da5_1
  - validators=0.18.2=pyhd3eb1b0_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=0.58.0=py312hca03da5_4
  - wheel=0.41.2=py312hca03da5_0
  - widgetsnbextension=4.0.10=py312hca03da5_0
  - xarray=2023.6.0=py312hca03da5_0
  - xz=5.4.6=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0